#!/usr/bin/env sh
# Gradle start up script for POSIX generated by Gradle.
# This is a minimal version - the actual wrapper jar will be downloaded by setup-gradle action.

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS detection
cygwin=false
darwin=false
nonstop=false
case "$(uname)" in
    CYGWIN*)
        cygwin=true
        ;;
    Darwin*)
        darwin=true
        ;;
    NonStop*)
        nonstop=true
        ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
    MAX_FD_LIMIT=$(ulimit -H -n) 2>/dev/null || MAX_FD_LIMIT=""
    case $MAX_FD_LIMIT in
        '' | soft) :;;
        *)
            ulimit -n `expr $MAX_FD_LIMIT - 1` >/dev/null 2>&1 || warn "Could not set maximum file descriptor limit to \`expr $MAX_FD_LIMIT - 1\`"
        ;;
    esac
fi

# Determine the APP_HOME directory
# Resolve links: $0 may be a link
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=$(ls -ld "$PRG")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=$(dirname "$PRG")"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Find the gradle wrapper jar
GRADLE_WRAPPER_JAR="$HOME/.gradle/wrapper/dists/gradle-8.5-bin"
for dir in $GRADLE_WRAPPER_JAR*; do
    if [ -f "$dir/gradle-8.5/bin/gradle" ]; then
        GRADLE_CMD="$dir/gradle-8.5/bin/gradle"
        break
    fi
done

# If we found the installed gradle, use it directly
if [ -n "$GRADLE_CMD" ] && [ -x "$GRADLE_CMD" ]; then
    exec "$GRADLE_CMD" "$@"
    exit $?
fi

# Otherwise, try to use the wrapper
if [ -f "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ]; then
    exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
else
    echo "Gradle wrapper JAR not found. Please run 'gradle wrapper' first or use the setup-gradle GitHub Action."
    exit 1
fi
